// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3zKYKBvU8xmR-tcM16V2LqmOcAqI0WOE',
    appId: '1:574272084535:web:4a20fcc67206450da97db2',
    messagingSenderId: '574272084535',
    projectId: 'wanderai-metrb',
    authDomain: 'wanderai-metrb.firebaseapp.com',
    storageBucket: 'wanderai-metrb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOEGypfJX3vsymic-9ro6m1xlu7uEE5Ao',
    appId: '1:574272084535:android:13d05bdec4355c77a97db2',
    messagingSenderId: '574272084535',
    projectId: 'wanderai-metrb',
    storageBucket: 'wanderai-metrb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGSIONLWMiPveE65uA_iBAkCGWutUmjDw',
    appId: '1:574272084535:ios:bd6e7973e0644310a97db2',
    messagingSenderId: '574272084535',
    projectId: 'wanderai-metrb',
    storageBucket: 'wanderai-metrb.firebasestorage.app',
    iosClientId: '574272084535-cgoj3gfsnljle5a5hvgppce5cb7htj2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGSIONLWMiPveE65uA_iBAkCGWutUmjDw',
    appId: '1:574272084535:ios:bd6e7973e0644310a97db2',
    messagingSenderId: '574272084535',
    projectId: 'wanderai-metrb',
    storageBucket: 'wanderai-metrb.firebasestorage.app',
    iosClientId: '574272084535-cgoj3gfsnljle5a5hvgppce5cb7htj2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3zKYKBvU8xmR-tcM16V2LqmOcAqI0WOE',
    appId: '1:574272084535:web:20895a36b17a939ea97db2',
    messagingSenderId: '574272084535',
    projectId: 'wanderai-metrb',
    authDomain: 'wanderai-metrb.firebaseapp.com',
    storageBucket: 'wanderai-metrb.firebasestorage.app',
  );

}